version: "3.9"
services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/data/db"
volumes:
  postgres_data: